// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EndToEnd.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EndToEnd.Features.TravelRequest")]
    public partial class EndToEnd_Features_TravelRequestFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "E2E.TravelRequest.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EndToEnd.Features.TravelRequest", "\tAs a Resolver\r\n\tI want to be able to submit a Travel Request on someones behalf\r" +
                    "\n\tthen log in as a resolver and complete the request", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("E2E.TravelRequest")]
        [NUnit.Framework.CategoryAttribute("dev")]
        [NUnit.Framework.CategoryAttribute("video")]
        public virtual void E2E_TravelRequest()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("E2E.TravelRequest", new string[] {
                        "dev",
                        "video"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am on the Login Form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When("I login with the username \'rttms.automated.testing\' and password \'autopass\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Given("I go to this url \'rttms/#/order/search\' and wait until I see the element with thi" +
                    "s class \'mdl-list\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.Then("I dismiss notifications", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.When("I request for \'Daniel Kereama\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("I should see \'Kereama, Daniel (IST-PIPEFISHPL)\' as the active requestor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.Given("I am on the \'Request Rio Tinto Projects Travel\' Form at \'rttms/#/order/item/RT_Pr" +
                    "ojects_Travel\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.Then("I dismiss notifications", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.Then("I check the \'urgent_travel_request\' check box field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
 testRunner.Then("I enter \'Mr Bob Dobalina\' in the \'requesting_for_passport_name\' text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.Then("I enter \'0749255511\' in the \'requesting_for_phone\' text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
 testRunner.Then("I select the \'Paraburdoo Mine Site\' option in the \'project_location\' list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
 testRunner.Then("In the \'grid_emergency_contacts\' grid I clear the existing rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
 testRunner.Then("In the \'grid_emergency_contacts\' grid I create a new row and enter the values \'Pa" +
                    "ddington Bear;071111111;041111111;cb:Personal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
 testRunner.Then("In the \'grid_emergency_contacts\' grid I create a new row and enter the values \'Bi" +
                    "ll Lumbergh;071111111;041111111;cb:Business\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
 testRunner.Then("I enter \'101\' random characters into the \'justification\' text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 29
 testRunner.Then("I check the \'approval_confirmation_check\' check box field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
 testRunner.Then("I select the \'International\' radio option from the \'trip_type\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.Then("I select the \'Return\' radio option from the \'trip_segments\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
 testRunner.Then("I enter \'Brisbane, Albert Street\' in the \'trip_origin\' autocomplete field and sel" +
                    "ect the first item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
 testRunner.Then("I enter \'Auckland International Airport\' in the \'trip_destination\' autocomplete f" +
                    "ield and select the first item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 34
 testRunner.Then("I select the \'Arriving as late as possible before\' option in the \'outward_date_re" +
                    "quirement\' list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 35
 testRunner.Then("I select the \'Arriving as late as possible before\' option in the \'return_date_req" +
                    "uirement\' list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.Then("I enter a date {1} days from now in the \'outward_date_time\' date time field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 37
 testRunner.Then("I enter a date {2} days from now in the \'return_date_time\' date time field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 38
 testRunner.Then("I check the \'additional_approval_check\' check box field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
 testRunner.Then("I select the \'Yes\' radio option from the \'approvals_required\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.Then("In the \'approvers_grid\' grid I clear the existing rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 41
 testRunner.Then("In the \'approvers_grid\' grid I create a new row and enter the values \'li:Managing" +
                    " Director (MD);cb:Brassard, Isabelle\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 42
 testRunner.Then("I select the \'Australia Dollars | AUD$\' option in the \'currency_of_cost\' list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 43
 testRunner.Then("I enter \'2314.00\' in the \'estimated_total_cost\' text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
 testRunner.Then("In the \'grid_cost_centre\' grid I enter the values \';;li:Cost centre;cb:10000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
 testRunner.Then("I enter \'This is a nice form\' in the \'comments\' text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.Then("I add an attachment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
 testRunner.When("I click the form submit button and wait for the page to finish loading", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
 testRunner.Then("I should see the title \'Thank you, your request has been submitted\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
 testRunner.Then("I remember my Unique Ticket Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
 testRunner.Given("I am on the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
 testRunner.Then("I impersonate as \'Susan Halloran\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 58
 testRunner.Then("I go to the \'Tickets\' List at \'sc_req_item_list.do\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 59
 testRunner.Then("I search the Resolver list \'sc_req_item\' by \'Number\' for my Unique Ticket Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
 testRunner.Then("I open the first list item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
 testRunner.Then("I click the \'Request Details\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
 testRunner.Then("I verify the \'urgent_travel_request\' request details check box field is checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
 testRunner.Then("I verify \'Mr Bob Dobalina\' exists in the \'requesting_for_passport_name\' request d" +
                    "etails text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
 testRunner.Then("I verify \'0749255511\' exists in the \'requesting_for_phone\' request details text f" +
                    "ield", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.Then("I verify the \'Paraburdoo Mine Site\' option is selected in the \'project_location\' " +
                    "request details list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
 testRunner.Then("I Verify the \'grid_emergency_contacts\' grid contains the row \'Paddington Bear;071" +
                    "111111;041111111;Personal\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 69
 testRunner.Then("I Verify the \'grid_emergency_contacts\' grid contains the row \'Bill Lumbergh;07111" +
                    "1111;041111111;Business\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 70
 testRunner.Then("I verify the \'approval_confirmation_check\' request details check box field is che" +
                    "cked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 71
 testRunner.Then("I verify the \'International\' option is selected from the \'trip_type\' request deta" +
                    "ils radio field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 72
 testRunner.Then("I verify the \'Return\' option is selected from the \'trip_segments\' request details" +
                    " radio field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
 testRunner.Then("I verify \'Brisbane, Albert Street\' exists in the \'trip_origin\' request details au" +
                    "tocomplete field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
 testRunner.Then("I verify \'Auckland International Airport\' exists in the \'trip_destination\' reques" +
                    "t details autocomplete field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
 testRunner.Then("I verify the \'Arriving as late as possible before\' option is selected in the \'out" +
                    "ward_date_requirement\' request details list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
 testRunner.Then("I verify the \'Arriving as late as possible before\' option is selected in the \'ret" +
                    "urn_date_requirement\' request details list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 80
 testRunner.Then("I verify the \'additional_approval_check\' request details check box field is check" +
                    "ed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.Then("I verify the \'Yes\' option is selected from the \'approvals_required\' request detai" +
                    "ls radio field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
 testRunner.Then("I Verify the \'approvers_grid\' grid contains the row \'Managing Director (MD);Brass" +
                    "ard, Isabelle\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
 testRunner.Then("I verify the \'Australia Dollars | AUD$\' option is selected in the \'currency_of_co" +
                    "st\' request details list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.Then("I verify \'2,314.00\' exists in the \'estimated_total_cost\' request details text fie" +
                    "ld", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
 testRunner.Then("I Verify the \'grid_cost_centre\' grid contains the row \'Cost centre;10000000 DEFAU" +
                    "LT CC CC1000\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 86
 testRunner.Then("I verify \'This is a nice form\' exists in the \'comments\' request details text fiel" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 89
 testRunner.Then("I remember the current Url for the \'Requested Item\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 92
 testRunner.Then("I click the \'Catalog Tasks\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 93
 testRunner.Then("I open the \'Seeking quote\' Catalog Task", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 94
 testRunner.Then("I select the \'Closed Complete\' option in the \'sc_task.state\' resolver select fiel" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 95
 testRunner.Then("I enter the text \'Automated Tester was here\' into the \'sc_task.description\' resol" +
                    "ver text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 96
 testRunner.Then("I click the \'Activity\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 97
 testRunner.Then("I enter the text \'Quote obtained: $2,314.00 flying Qantas flight 2345\' into the \'" +
                    "activity-stream-comments-textarea\' resolver text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 98
 testRunner.Then("I click the Complete Task button and wait for the form to reload", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 99
 testRunner.Then("I return to the Url I remembered for the \'Requested Item\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 102
 testRunner.Then("I click the \'Catalog Tasks\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
 testRunner.Then("I open the \'Seeking approval\' Catalog Task", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.Then("I select the \'Closed Complete\' option in the \'sc_task.state\' resolver select fiel" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
 testRunner.Then("I click the \'Activity\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
 testRunner.Then("I enter the text \'Quote approved by Automated Tester\' into the \'activity-stream-c" +
                    "omments-textarea\' resolver text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
 testRunner.Then("I click the Request Approvals button and wait for the form to reload", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 108
 testRunner.Then("I return to the Url I remembered for the \'Requested Item\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 111
 testRunner.Then("I click the \'Catalog Tasks\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 112
 testRunner.Then("I open the \'Processing Booking\' Catalog Task", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
 testRunner.Then("I select the \'Closed Complete\' option in the \'sc_task.state\' resolver select fiel" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 114
 testRunner.Then("I click the \'Activity\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 115
 testRunner.Then("I enter the text \'Itinerary sent to customer\' into the \'activity-stream-comments-" +
                    "textarea\' resolver text field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
 testRunner.Then("I click the \'Request Details\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 117
 testRunner.Then("I set the option \'Yes\' on the \'travel_booked\' request details radio group", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 118
 testRunner.Then("I set the value \'Flight booked by Automated tester\' on the \'customer_message\' req" +
                    "uest details textbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 119
 testRunner.Then("I include the first Itenerary attachment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 120
 testRunner.Then("I click the Complete Task button, accept alerts and wait for the form to reload", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 123
 testRunner.Given("I am on the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 124
 testRunner.Then("I impersonate as \'Daniel Kereama\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
 testRunner.Given("I go to this url \'rttms/#/track/search/all\' and wait until I see the element with" +
                    " this class \'mdl-list\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 128
 testRunner.Then("I click the Advanced filter options button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 129
 testRunner.Then("I select the Status All filter option and wait for results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 130
 testRunner.Then("I search Track for my Unique Ticket Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 131
 testRunner.Then("I click the search result link for my Unique Ticket Number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
 testRunner.Then("I verify my Ticket status is \'Closed Complete\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
